name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout source code
      uses: actions/checkout@v3

    # Установка JDK 17
    - name: Set up JDK 17 and Maven 3.9.2
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'
        cache: 'maven' # Кэширование зависимостей Maven
        maven-version: '3.9.2'

    # Сборка и тестирование с Maven
    - name: Build and Test
      run: mvn clean verify

    # Сохранение артефакта сборки
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: target/*.jar

    # Вход в GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Сборка Docker-обраа
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/hello-world:latest .

    # Публикация Docker-обраа в GitHub Container Registry
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/hello-world:latest
